version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    cooldown:
      default-days: 3
    commit-message:
      prefix: chore
    labels: []
    groups:
      frontend:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    commit-message:
      prefix: chore
    labels: []
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
