name: Lint
on: push

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Lint
        run: bun run ci
